### ISSUE TITLE
Generate component with react/addons

### ISSUE THREAD

**Issue by cezarsmpio** [weblogixx/generator-react-webpack-alt#1]
Hi, when I generate a new component, the import comes `import React from 'react/addons';``

Error:

```
Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.
```

Remove /addons resolves.

**Comment by weblogixx** [comment]
Hi @CezarLuiz0,

this bug is fixed with the latest release of this generators parent project, Generator-React-Webpack. If you update your generator-react-webpack-alt, it should draw generator-react-webpack@2.2.3 where this problem is not there anymore.

Also your unit tests will look a bit different. It should be easily patchable, through.

**Comment by cezarsmpio** [comment]
Hi @weblogixx ,

Thanks for the information! Have a good day ;)

**Comment by weblogixx** [comment]
You are welcome :-).

**Comment by cezarsmpio** [comment]
Hi @weblogixx, I updated Generator-React-Webpack and the problem is still there.

**Comment by weblogixx** [comment]
Hi @CezarLuiz0, did you create a new component in your project? Currently there is no way to "migrate" older, already created components when there is an update to the generator. If files are written, they are written, only newly generated components will look different. Unfortunately, there is no update system available for older generated components.

However, if you have the problem when creating new components, this is another thing. Please try the following:
- Just in case you are using nvm (the node version manager): Make sure you update the global npm package in the current running node version. I tried to debug the generator once and it took me half an hour to find out I had changed to a node version with an older package version.
- Just to be sure, update the generator via `npm update -g`. This should install the latest version for generator-react-webpack-alt. As of today, you should at least see that the generator updates its dependency generator-react-webpack to version 2.5.6. This version definitively has the update for React 0.14.
- Create a new project (yo react-webpack-alt) and create a new component in it. If there is still the wrong path in it, please post the output of `npm ls -g`. There should be version numbers for the generator, yo and so forth. Eventually the update did not work as expected.

Last: I know that updating current projects is a pain. The small development cycles of the parent project and the constant evolving of REACT does not make it easier. Like I said earlier, maybe we could think of a simple approach of updating older project files when creating new components. However, currently there are no definitive plans for such a feature :(. 

Hope this helps.
